In [1]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


In [2]:
import tensorflow as tf
tf.__version__

'2.1.0'

In [0]:
from tensorflow.keras.preprocessing.text import  Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [0]:
# Just a simple test
sentences = [
             'I like eggs and ham.',
             'I love chocolate and bunnies',
             'I hate onions.'
]

In [0]:
MAX_VOCAB_SIZE = 20000
tokenizer = Tokenizer(num_words = MAX_VOCAB_SIZE)
tokenizer.fit_on_texts(sentences)
sequences = tokenizer.texts_to_sequences(sentences)

In [10]:
print(sequences)

[[1, 3, 4, 2, 5], [1, 6, 7, 2, 8], [1, 9, 10]]


In [12]:
# Word to index mapping
tokenizer.word_index

{'and': 2,
 'bunnies': 8,
 'chocolate': 7,
 'eggs': 4,
 'ham': 5,
 'hate': 9,
 'i': 1,
 'like': 3,
 'love': 6,
 'onions': 10}

In [13]:
# Use the defaults
data = pad_sequences(sequences)
print(data)

[[ 1  3  4  2  5]
 [ 1  6  7  2  8]
 [ 0  0  1  9 10]]


In [21]:
# Post padding
MAX_SEQUENCE_LENGTH = 5
data = pad_sequences(sequences, maxlen = MAX_SEQUENCE_LENGTH, padding = 'post')
print(data)

[[ 1  3  4  2  5]
 [ 1  6  7  2  8]
 [ 1  9 10  0  0]]


In [22]:
# Too much PADDING
MAX_SEQUENCE_LENGTH = 8
data = pad_sequences(sequences, maxlen = MAX_SEQUENCE_LENGTH)
print(data)

[[ 0  0  0  1  3  4  2  5]
 [ 0  0  0  1  6  7  2  8]
 [ 0  0  0  0  0  1  9 10]]


In [24]:
# Too less padding - TRUNCATION
MAX_SEQUENCE_LENGTH = 3
data = pad_sequences(sequences, maxlen = MAX_SEQUENCE_LENGTH)
print(data)

[[ 4  2  5]
 [ 7  2  8]
 [ 1  9 10]]


In [25]:
# Post Truncation
MAX_SEQUENCE_LENGTH = 3
data = pad_sequences(sequences, maxlen = MAX_SEQUENCE_LENGTH, truncating = 'post')
print(data)

[[ 1  3  4]
 [ 1  6  7]
 [ 1  9 10]]
